<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-LTESystemMonitorAgent-e9f2c66d-f908-4a1f-b11f-b4b1aa011b9b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.8" />
    <PackageReference Include="NLog.Extensions.Logging" Version="6.1.3" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.18.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LTESM.DAL.SQLite\LTESM.DAL.SQLite.csproj" />
    <ProjectReference Include="..\LTESystemMonitoring\LTESystemMonitoring.csproj" />
    <ProjectReference Include="..\LTESystemMonitoring.Abstractions\LTESystemMonitoring.Abstractions.csproj" />
    <ProjectReference Include="..\LTESystemOutbox\LTESystemOutbox.csproj" />
    <ProjectReference Include="..\LTESystemOutbox.Abstractions\LTESystemOutbox.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="nlog.config" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
