// <auto-generated />
using System;
using LTESM.DAL.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LTESM.DAL.SQLite.Migrations
{
    [DbContext(typeof(SQLiteDbContext))]
    partial class SQLiteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("LTESM.DAL.Abstractions.Entities.Metric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<long>("AvailableMemoryBytes")
                        .HasColumnType("integer")
                        .HasColumnName("available_memory_bytes");

                    b.Property<DateTimeOffset>("CollectedAtUtc")
                        .HasColumnType("text")
                        .HasColumnName("collected_at_utc");

                    b.Property<double>("CpuUsagePercent")
                        .HasColumnType("real")
                        .HasColumnName("cpu_usage_percent");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hostname");

                    b.Property<double>("RamUsagePercent")
                        .HasColumnType("real")
                        .HasColumnName("ram_usage_percent");

                    b.Property<long>("TotalMemoryBytes")
                        .HasColumnType("integer")
                        .HasColumnName("total_memory_bytes");

                    b.Property<long>("UptimeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("uptime_seconds");

                    b.Property<string>("WindowsVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("windows_version");

                    b.HasKey("Id");

                    b.ToTable("metric", (string)null);
                });

            modelBuilder.Entity("LTESM.DAL.Abstractions.Entities.MetricDiskSpace", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("DriveFormat")
                        .HasColumnType("text")
                        .HasColumnName("drive_format");

                    b.Property<long>("FreeSpaceBytes")
                        .HasColumnType("integer")
                        .HasColumnName("free_space_bytes");

                    b.Property<long>("MetricId")
                        .HasColumnType("integer")
                        .HasColumnName("metric_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("TotalSpaceBytes")
                        .HasColumnType("integer")
                        .HasColumnName("total_space_bytes");

                    b.Property<string>("VolumeLabel")
                        .HasColumnType("text")
                        .HasColumnName("volume_label");

                    b.HasKey("Id");

                    b.HasIndex("MetricId");

                    b.ToTable("metric_disk_space", (string)null);
                });

            modelBuilder.Entity("LTESM.DAL.Abstractions.Entities.MetricIpAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("AddressFamily")
                        .HasColumnType("text")
                        .HasColumnName("address_family");

                    b.Property<long>("MetricId")
                        .HasColumnType("integer")
                        .HasColumnName("metric_id");

                    b.Property<string>("NetworkInterfaceName")
                        .HasColumnType("text")
                        .HasColumnName("network_interface_name");

                    b.HasKey("Id");

                    b.HasIndex("MetricId");

                    b.ToTable("metric_ip_address", (string)null);
                });

            modelBuilder.Entity("LTESM.DAL.Abstractions.Entities.MetricMonitoredProcess", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("integer")
                        .HasColumnName("is_running");

                    b.Property<int>("MatchedProcessCount")
                        .HasColumnType("integer")
                        .HasColumnName("matched_process_count");

                    b.Property<long>("MetricId")
                        .HasColumnType("integer")
                        .HasColumnName("metric_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("MetricId");

                    b.ToTable("metric_monitored_process", (string)null);
                });

            modelBuilder.Entity("LTESM.DAL.Abstractions.Entities.MetricOutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("text")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<long>("MetricId")
                        .HasColumnType("integer")
                        .HasColumnName("metric_id");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("text")
                        .HasColumnName("sent_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("MetricId")
                        .IsUnique();

                    b.HasIndex("Status", "Id");

                    b.ToTable("metric_outbox_message", (string)null);
                });

            modelBuilder.Entity("LTESM.DAL.Abstractions.Entities.MetricProcess", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<long>("MetricId")
                        .HasColumnType("integer")
                        .HasColumnName("metric_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("ProcessId")
                        .HasColumnType("integer")
                        .HasColumnName("process_id");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("text")
                        .HasColumnName("started_at_utc");

                    b.Property<long?>("WorkingSetBytes")
                        .HasColumnType("integer")
                        .HasColumnName("working_set_bytes");

                    b.HasKey("Id");

                    b.HasIndex("MetricId");

                    b.ToTable("metric_process", (string)null);
                });

            modelBuilder.Entity("LTESM.DAL.Abstractions.Entities.MetricDiskSpace", b =>
                {
                    b.HasOne("LTESM.DAL.Abstractions.Entities.Metric", "Metric")
                        .WithMany("DiskSpaces")
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("LTESM.DAL.Abstractions.Entities.MetricIpAddress", b =>
                {
                    b.HasOne("LTESM.DAL.Abstractions.Entities.Metric", "Metric")
                        .WithMany("IpAddresses")
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("LTESM.DAL.Abstractions.Entities.MetricMonitoredProcess", b =>
                {
                    b.HasOne("LTESM.DAL.Abstractions.Entities.Metric", "Metric")
                        .WithMany("MonitoredProcesses")
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("LTESM.DAL.Abstractions.Entities.MetricOutboxMessage", b =>
                {
                    b.HasOne("LTESM.DAL.Abstractions.Entities.Metric", "Metric")
                        .WithOne("OutboxMessage")
                        .HasForeignKey("LTESM.DAL.Abstractions.Entities.MetricOutboxMessage", "MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("LTESM.DAL.Abstractions.Entities.MetricProcess", b =>
                {
                    b.HasOne("LTESM.DAL.Abstractions.Entities.Metric", "Metric")
                        .WithMany("RunningProcesses")
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metric");
                });

            modelBuilder.Entity("LTESM.DAL.Abstractions.Entities.Metric", b =>
                {
                    b.Navigation("DiskSpaces");

                    b.Navigation("IpAddresses");

                    b.Navigation("MonitoredProcesses");

                    b.Navigation("OutboxMessage");

                    b.Navigation("RunningProcesses");
                });
#pragma warning restore 612, 618
        }
    }
}
